apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-tallinn
  namespace: tallinn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: ghcr.io/tluhk/todo@sha256:224a8952840334fbf206eb972404c20378257d3e6832fd5654abdda70d56a9f8
          env:
            - name: COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: COMPANY_NAME
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret
