apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-haapsalu
  namespace: haapsalu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: todo
          image: ghcr.io/tluhk/todo:latest
          env:
            - name: COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: COMPANY_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: PORT
          ports:
            - containerPort: 8081
