apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-haapsalu
  namespace: haapsalu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: todo
          image: ghcr.io/tluhk/todo:latest
          env:
            - name: COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: COMPANY_NAME
            - name: REDIS_HOST
              value: "redis-service" # Kasutab Redis Service DNS-i
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 3000
